name: ci-expensive

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  expensive:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run-expensive-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm run test:expensive
